function inicio_comercio(e){
    let copia = JSON.parse(JSON.stringify(e));
    return copia;
}

const comercio_prado_1 = {nombre: "Comerciante Alex", conoce: false, finInventario: ["Comerciante Alex: ¡Me ha quedado sin existencias!","Comerciante Alex: ¡Muchas gracias por comprarlo todo!"], cabezal: "Tienda ambulante de Alex", src: "https://image.lexica.art/full_jpg/123d6551-e8a7-4c07-86d2-b71cd412ef9d",
frases: [
    "Que alegría poder encontrar a alguien amable en estos prados.",
    "Espero que el tiempo aguante.",
    "Me pregunto qué clase de criaturas viven en estos prados.",
    "Espero no encontrarme con ningún bandido.",
    "Me pregunto cuánto falta para llegar a la próxima ciudad.",
    "Estoy empezando a tener hambre.",
    "Me gustaría descansar un rato.",
    "Me pregunto qué clase de animales viven en estos bosques.",
    "Espero no encontrarme con ningún monstruo.",
    "Me pregunto cuánto falta para llegar a la próxima aldea.",
    "Estoy empezando a tener sed.",
    "Me gustaría beber algo de agua.",
    "Me pregunto qué clase de gente vive en esta zona.",
    "Espero no encontrarme con ningún mago malvado.",
    "Me pregunto cuánto falta para llegar a mi destino.",
    "Estoy empezando a tener frío.",
    "Me gustaría abrigarme.",
    "Me pregunto qué clase de aventuras me esperan en esta tierra.",
    "Espero no tener que luchar contra ningún dragón.",
    "Me pregunto cuánto falta para llegar a la próxima gran ciudad.",
    "Estoy empezando a tener miedo.",
    "Me gustaría estar en casa.",
    "Me pregunto qué clase de peligros me esperan en este mundo.",
    "Espero poder sobrevivir.",
    "Me pregunto cuánto falta para llegar a la próxima frontera.",
    "Estoy empezando a perder la esperanza.",
    "Me gustaría rendirme.",
    "Me pregunto qué clase de futuro me espera en este mundo.",
    "Espero poder encontrar mi lugar en la vida.",
    "Me pregunto cuánto falta para llegar a la próxima aventura.",
    "Estoy empezando a sentirme emocionado.",
    "Me gustaría vivir muchas más aventuras.",
    "Me pregunto qué clase de cosas me esperan en este mundo.",
    "Espero poder ver y hacer muchas cosas.",
    "Me pregunto cuánto falta para llegar a la próxima gran cosa.",
    "Estoy empezando a sentir curiosidad.",
    "Me gustaría aprender muchas cosas nuevas.",
    "Me pregunto qué clase de personas me esperan en este mundo.",
    "Espero poder conocer muchas personas.",
    "Me pregunto cuánto falta para llegar a la próxima gran reunión.",
    "Estoy empezando a sentirme feliz."
],
inventario : [
    {name : "Legumbres", desc : "Delicioso alimento muy rico vitaminicamente, da mucha energía", precio : 15, bioma : "Poblado", cantidad : 3},
    {name : "Piedra Rúnica", desc : "Piedra de un brillo azulado con unas marcas y símbolos extraños e incomprensibles...", precio : 100, bioma : "Prado", cantidad : 1},
    {name : "Daga", desc : "Muy afilada y de corto alcance, es el arma más usada para hacer traiciones", precio : 150, bioma : "Prado", cantidad : 1},
    {name : "Ballesta", desc : "Artefacto hecho de madera con un conjunto de engranajes que permiten  tensar la cuerda y lanzar flechas capaces de perforar armaduras, muchos caballeros la detestan", precio : 200, bioma : "Prado", cantidad : 1},
    {name : "Flores Silvestres", desc : "Conjunto de flores hermosas que tienen un aroma muy embriagador", precio : 15, bioma : "Prado", cantidad : 5},
    {name : "Bayas Silvestres", desc : "Unas bayas que crecen en los prados, ¡su sabor es sumamente dulce y delicioso!", precio : 8, bioma : "Prado", cantidad : 10},
]};

const comercio_sirena = {nombre: "Sirena", finInventario: ["Sirena: ¡Ya no tengo nada más que ofrecerte!","Sirena: ¡Muchas gracias viajero por tus servicios!"], cabezal: "Objetos del mar", src: "https://image.lexica.art/full_jpg/0f50af94-aa58-434d-9cd3-178fc4677603",
frases: [
    "El mar es un lugar inmenso, Un mundo lleno de vida. Hay peces de todos colores, Y criaturas grandes y pequeñas.",
    "Mar, eres el espejo del cielo, un mar de azules y verdes, un mar de sueños y misterios.",
    "El mar es un lugar maravilloso, Un lugar lleno de secretos. Es un lugar donde puedes perderte, Y encontrarte a ti mismo.",
    "En tus aguas cristalinas, los peces nadan libres, las ballenas juegan, y los delfines saltan.",
    "El mar es un lugar peligroso, Un lugar donde la tormenta puede golpear de repente. Pero también es un lugar hermoso, Un lugar donde puedes sentir la paz.",
    "En tus costas arenosas, los niños juegan, los enamorados se besan, y los viejos se sientan a recordar.",
    "El mar es un lugar maravilloso, Un lugar lleno de secretos. Es un lugar donde puedes perderte, Y encontrarte a ti mismo.",
    "En tus olas bravías, los barcos navegan, los pescadores faenan, y los piratas se esconden.",
    "El mar es un lugar de contrastes, Un lugar donde la calma y la tormenta se encuentran. Es un lugar donde la vida y la muerte coexisten.",
    "En tus aguas profundas, los tesoros se esconden, las sirenas habitan, y los monstruos marinos se ocultan.",
    "El mar es un lugar maravilloso, Un lugar lleno de secretos. Es un lugar donde puedes perderte, Y encontrarte a ti mismo.",
    "Mar, eres un lugar mágico, un lugar de sueños y aventuras, un lugar donde todo es posible.",
    "El mar es un lugar misterioso, Un lugar que nunca deja de sorprender. Es un lugar que siempre nos llama, Y nunca podemos dejar de ir.",
    "Mar, nos enseñas la belleza de la naturaleza, nos enseñas el poder de la vida, y nos enseñas el misterio del universo.",
    "Mar, eres un regalo de la naturaleza, un regalo que debemos cuidar, un regalo que debemos preservar.",
    "Mar, eres el espejo del cielo, un mar de azules y verdes, un mar de sueños y misterios."
],
inventario : [
    {name : "Algas Marinas", desc : "No hay mucho que describir, puedes lanzarlas por la borda o cocinarlas (aunque su sabor no sea muy agradable)", precio : 5, bioma : "Mar", cantidad : 20},
    {name : "Escamas de Coral", desc : "Escamas grandes pertenecientes a alguna misteriosa criatura de las profundidades", precio : 150, bioma : "Mar", cantidad : 3},
    {name : "Cola de Tritón", desc : "Bella cola perteneciente a algún tritón que la habrá perdido para su desgracia", precio : 150, bioma : "Mar", cantidad : 3},
    {name : "Espuma de Sirena", desc : "Preciosas perlas color azulado muy raras de encontrar en la mar, según se dice, se forman con la última palabra una sirena", precio : 150, bioma : "Playa", cantidad : 3},
    {name : "Escudo de Arena", desc : "Escudo formado por diversas capas de arena que se van intercalando entre sí, ¡Aunque no lo parezca es muy resistente!", precio : 250, bioma : "Playa", cantidad : 2},
    {name : "Concha Marina", desc : "Bonita concha decorativa la cual puede alcanzar un buen precio en el mercado", precio : 100, bioma : "Playa", cantidad : 5},
    {name : "Pescado Fresco", desc : "¿A quien no le gusta este buen manjar de la mar?", precio : 20, bioma : "Playa", cantidad : 15},
    {name : "Romboide de arena celeste", desc : "Extraño artefacto que guarda en su interior un extraño y misterioso poder; dicen las leyendas que quien lo deshaga se podrá teletransportar", precio : 300, bioma : "Mar", cantidad : 1},
]};

const comercio_prado_2 = {nombre: "Comerciante Juan", conoce: false, finInventario: ["Comerciante Juan: ¡Ya no me queda nada!","Comerciante Juan: ¡Muchas gracias por comprarlo todo!"], cabezal: "Tienda de Juan", src: "https://image.lexica.art/full_jpg/4ce34a46-6d92-40aa-b51d-f5b5717d6f31", hola : "Que hay forastero.",adios : "¡Nos vemos forastero!",
frases: [
    "Que alegría poder encontrar a alguien amable en estos prados.",
    "Espero que el tiempo aguante.",
    "Me pregunto qué clase de criaturas viven en estos prados.",
    "Espero no encontrarme con ningún bandido.",
    "Me pregunto cuánto falta para llegar a la próxima ciudad.",
    "Estoy empezando a tener hambre.",
    "Me gustaría descansar un rato.",
    "Me pregunto qué clase de animales viven en estos bosques.",
    "Espero no encontrarme con ningún monstruo.",
    "Me pregunto cuánto falta para llegar a la próxima aldea.",
    "Estoy empezando a tener sed.",
    "Me gustaría beber algo de agua.",
    "Me pregunto qué clase de gente vive en esta zona.",
    "Espero no encontrarme con ningún mago malvado.",
    "Me pregunto cuánto falta para llegar a mi destino.",
    "Estoy empezando a tener frío.",
    "Me gustaría abrigarme.",
    "Me pregunto qué clase de aventuras me esperan en esta tierra.",
    "Espero no tener que luchar contra ningún dragón.",
    "Me pregunto cuánto falta para llegar a la próxima gran ciudad.",
    "Estoy empezando a tener miedo.",
    "Me gustaría estar en casa.",
    "Me pregunto qué clase de peligros me esperan en este mundo.",
    "Espero poder sobrevivir.",
    "Me pregunto cuánto falta para llegar a la próxima frontera.",
    "Estoy empezando a perder la esperanza.",
    "Me gustaría rendirme.",
    "Me pregunto qué clase de futuro me espera en este mundo.",
    "Espero poder encontrar mi lugar en la vida.",
    "Me pregunto cuánto falta para llegar a la próxima aventura.",
    "Estoy empezando a sentirme emocionado.",
    "Me gustaría vivir muchas más aventuras.",
    "Me pregunto qué clase de cosas me esperan en este mundo.",
    "Espero poder ver y hacer muchas cosas.",
    "Me pregunto cuánto falta para llegar a la próxima gran cosa.",
    "Estoy empezando a sentir curiosidad.",
    "Me gustaría aprender muchas cosas nuevas.",
    "Me pregunto qué clase de personas me esperan en este mundo.",
    "Espero poder conocer muchas personas.",
    "Me pregunto cuánto falta para llegar a la próxima gran reunión.",
    "Estoy empezando a sentirme feliz."
],
inventario : [
    {name : "Legumbres", desc : "Delicioso alimento muy rico vitaminicamente, da mucha energía", precio : 20, bioma : "Poblado", cantidad : 3},
    {name : "Piedra Rúnica", desc : "Piedra de un brillo azulado con unas marcas y símbolos extraños e incomprensibles...", precio : 200, bioma : "Prado", cantidad : 1},
    {name : "Daga", desc : "Muy afilada y de corto alcance, es el arma más usada para hacer traiciones", precio : 250, bioma : "Prado", cantidad : 1},
    {name : "Ballesta", desc : "Artefacto hecho de madera con un conjunto de engranajes que permiten  tensar la cuerda y lanzar flechas capaces de perforar armaduras, muchos caballeros la detestan", precio : 350, bioma : "Prado", cantidad : 1},
    {name : "Flores Silvestres", desc : "Conjunto de flores hermosas que tienen un aroma muy embriagador", precio : 30, bioma : "Prado", cantidad : 5},
    {name : "Bayas Silvestres", desc : "Unas bayas que crecen en los prados, ¡su sabor es sumamente dulce y delicioso!", precio : 15, bioma : "Prado", cantidad : 10},
    {name : "Pan", desc : "Objeto redondo, blando y huele muy bien. Alimento básico en cualquier cultura", tag_inventario: "Usar", precio : 5, bioma : "Poblado", cantidad : 8},
    {name : "Bizcocho", desc : "Preparado y recién horneado... ¡Tiene muy buena pinta!", tag_inventario: "Usar", precio : 30, bioma : "Poblado", cantidad : 2},
    {name : "Cristal de la confianza", desc : "Extraño objeto de color rosado cristalino, al mirarlo te resulta muy acogedor y familiar.", tag_inventario: "Usar", precio : 300, bioma : "Poblado", cantidad : 1}
]};

const comercio_bosque = {nombre: "Comerciante Sofía", conoce: false, finInventario: ["Comerciante Sofía: ¡No tengo más productos!","Comerciante Sofía: ¡Muchas gracias por comprarlo todo!"], cabezal: "Tienda de Sofía", src: "https://image.lexica.art/full_jpg/12f3c03f-be58-4f41-9ae2-9b560d6291a9", hola : "Así que has venido a por remedios del bosque.",adios : "¡Que tus caminos estén despejados!",
frases: [
    "Qué alegría poder encontrar a alguien amable en este bosque frondoso.",
    "Espero que la naturaleza se mantenga en equilibrio.",
    "Me pregunto qué tipo de criaturas habitan en este hermoso bosque.",
    "Espero no perturbar la armonía de este ecosistema.",
    "Me pregunto cuánto falta para llegar al próximo claro en el bosque.",
    "Estoy empezando a sentir la conexión con la tierra.",
    "Me gustaría descansar un rato bajo la sombra de estos árboles.",
    "Me pregunto qué especies de animales viven en este exuberante bosque.",
    "Espero no encontrarme con ninguna actividad destructiva aquí.",
    "Me pregunto cuánto falta para llegar a la próxima aldea rural.",
    "Estoy empezando a sentirme parte de este entorno natural.",
    "Me gustaría beber agua de un arroyo cristalino.",
    "Me pregunto qué clase de personas eligen vivir en armonía con la naturaleza.",
    "Espero no encontrarme con ningún daño ambiental en mi camino.",
    "Me pregunto cuánto falta para llegar a mi destino en medio de este bosque.",
    "Estoy empezando a sentir la frescura del aire boscoso.",
    "Me gustaría abrigarme con el calor de la naturaleza.",
    "Me pregunto qué emocionantes aventuras me aguardan en este bosque.",
    "Espero no tener que enfrentar ninguna amenaza a la biodiversidad.",
    "Me pregunto cuánto falta para llegar a la próxima área protegida.",
    "Estoy empezando a sentirme en paz con la naturaleza que me rodea.",
    "Me gustaría estar en sintonía con el ciclo natural de la vida.",
    "Me pregunto qué secretos y maravillas me aguardan en este mundo natural.",
    "Espero poder contribuir a la conservación de estos bosques.",
    "Me pregunto cuánto falta para llegar a la próxima aventura ecológica.",
    "Estoy empezando a sentirme inspirado por la biodiversidad que me rodea.",
    "Me gustaría aprender más sobre los ecosistemas y sus interacciones.",
    "Me pregunto qué personas comparten mi amor por la naturaleza y el bosque.",
    "Espero poder conectar con otros amantes de la vida silvestre.",
    "Me pregunto cuánto falta para llegar a la próxima reunión en la naturaleza.",
    "Estoy empezando a sentirme feliz en medio de este entorno natural."
    ],
inventario : [
    {name : "Flores Silvestres", desc : "Conjunto de flores hermosas que tienen un aroma muy embriagador", precio : 30, bioma : "Prado", cantidad : 25},
    {name : "Bayas Silvestres", desc : "Unas bayas que crecen en los prados, ¡su sabor es sumamente dulce y delicioso!", precio : 15, bioma : "Prado", cantidad : 5},
    {name : "Setas", desc : "Estas son muy comunes por los bosques de la zona, están muy buenas salteadas", precio : 15, bioma : "Bosque", cantidad : 15},
    {name : "Tallo del Bosque", desc : "Hermoso tallo crecido unos arbustos específicos de la zona, sirve para hacer algunos brebajes, se puede vender a un precio razonable", precio : 20, bioma : "Bosque", cantidad : 10},
    {name : "Gota del alba", desc : "Gota formada por el rocío de cierto árbol mítico, se dice que puede aumentar a la vida a su portador", tag_inventario: "Usar", precio : 350, bioma : "Bosque", cantidad : 3},
    {name : "Espada hoja", desc : "Espada hecha de una especie de hoja fina y cortante, es increíblemente ligera pero parece no tener mucha durabilidad", tag_inventario: "Equipar", precio : 50, bioma : "Bosque", cantidad : 5},
    {name : "Bola de humo", desc : "Objeto circular con nubes en su interior creado a partir de densas nieblas concentradas ¡Si lo rompes puedes escabullirte con facilidad!", tag_inventario: "Usar", precio : 50, bioma : "Bosque", cantidad : 3},
    {name : "Barca", desc : "Bote de madera que te permite navegar por los mares", tag_inventario: "Usar", precio : 150, bioma : "Playa", cantidad : 1},
    {name : "Cristal de la confianza", desc : "Extraño objeto de color rosado cristalino, al mirarlo te resulta muy acogedor y familiar.", tag_inventario: "Usar", precio : 300, bioma : "Poblado", cantidad : 1}
]};

const comercio_playa = {nombre: "Comerciante Raquel", conoce: false, finInventario: ["Comerciante Raquel: ¡No tengo existencias!","Comerciante Raquel: ¡Muchas gracias por comprarlo todo!"], cabezal: "Tienda de Raquel", src: "https://image.lexica.art/full_jpg/74ade0fa-2541-4c25-ba7c-603509a2c7ad", hola : "Bienvenid@.",adios : "¡Espero que tus aguas estén en calma!",
frases: [
    "Qué alegría poder encontrar a alguien amable en estas playas.",
    "Espero que el clima se mantenga tranquilo.",
    "Me pregunto qué tipos de criaturas habitan en estas aguas.",
    "Espero no toparme con ninguna tormenta.",
    "Me pregunto cuánto falta para llegar a la próxima isla.",
    "Estoy empezando a tener sed de salinidad.",
    "Me gustaría descansar un rato junto a las olas.",
    "Me pregunto qué especies marinas habitan en este océano.",
    "Espero no encontrarme con ningún tiburón en mi camino.",
    "Me pregunto cuánto falta para llegar al siguiente puerto.",
    "Estoy empezando a sentir la brisa marina en mi piel.",
    "Me gustaría sentir el sabor del agua salada.",
    "Me pregunto qué tipo de historias tienen los marineros de esta región.",
    "Espero no encontrarme con ninguna sirena encantadora.",
    "Me pregunto cuánto falta para llegar a la próxima bahía.",
    "Estoy empezando a disfrutar del fresco aire marino.",
    "Me gustaría abrigarme con una suave brisa marina.",
    "Me pregunto qué aventuras me aguardan en estas aguas.",
    "Espero no tener que enfrentar ninguna tormenta perfecta.",
    "Me pregunto cuánto falta para llegar a la próxima isla desierta.",
    "Estoy empezando a sentir la emoción de la navegación.",
    "Me gustaría vivir muchas más travesías marítimas.",
    "Me pregunto qué tesoros naturales me aguardan en este océano.",
    "Espero poder sobrevivir a las aguas más turbulentas.",
    "Me pregunto cuánto falta para llegar al próximo puerto seguro.",
    "Estoy empezando a perderme en la inmensidad del mar.",
    "Me gustaría rendirme a la belleza del océano.",
    "Me pregunto qué horizontes me depara este vasto mundo marino.",
    "Espero poder encontrar mi rumbo en esta vida marítima.",
    "Me pregunto cuánto falta para la próxima gran travesía.",
    "Estoy empezando a sentirme sumergido en la aventura.",
    "Me gustaría aprender todos los secretos del mar.",
    "Me pregunto qué marineros y pescadores me esperan en este mundo.",
    "Espero poder compartir historias con muchos amantes del mar.",
    "Me pregunto cuánto falta para la próxima gran regata.",
    "Estoy empezando a sentirme feliz con solo mirar al horizonte marino."
    ],
inventario : [
    {name : "Concha Marina", desc : "Bonita concha decorativa la cual puede alcanzar un buen precio en el mercado", tag_inventario: "Vender", precio : 90, bioma : "Playa", cantidad : 3},
    {name : "Pescado Fresco", desc : "¿A quien no le gusta este buen manjar de la mar?", tag_inventario: "Usar", precio : 20, bioma : "Playa", cantidad : 15},
    {name : "Escudo de Arena", desc : "Escudo formado por diversas capas de arena que se van intercalando entre sí, ¡Aunque no lo parezca es muy resistente!", tag_inventario: "Equipar", precio : 250, bioma : "Playa", cantidad : 2},
    {name : "Espuma de Sirena", desc : "Preciosas perlas color azulado muy raras de encontrar en la mar, según se dice, se forman con la última palabra una sirena", tag_inventario: "Usar", precio : 350, bioma : "Playa", cantidad : 2},
    {name : "Algas Marinas", desc : "No hay mucho que describir, puedes lanzarlas por la borda o cocinarlas (aúnque su sabor no sea muy agradable)", tag_inventario: "Usar", precio : 1, bioma : "Mar", cantidad : 45},
    {name : "Barca", desc : "Bote de madera que te permite navegar por los mares", tag_inventario: "Usar", precio : 150, bioma : "Playa", cantidad : 1},
    {name : "Cristal de la confianza", desc : "Extraño objeto de color rosado cristalino, al mirarlo te resulta muy acogedor y familiar.", tag_inventario: "Usar", precio : 300, bioma : "Poblado", cantidad : 1}
]};

const comercio_montaña = {nombre: "Herrero Ferrán", conoce: false, finInventario: ["Herrero Ferrán: ¡No tengo más objetos!","Herrero Ferrán: ¡Muchas gracias por comprarlo todo!"], cabezal: "Tienda de Ferrán", src: "https://image.lexica.art/full_jpg/123d0d1c-07c5-4314-8b7d-facd07501960", hola : "Hola.",adios : "Adiós.",
frases: [
    "Qué alegría poder encontrar a alguien con habilidades en estos talleres de forja.",
    "Espero que el fuego de la fragua nunca se apague.",
    "Me pregunto qué tipo de metales se utilizan en estas creaciones.",
    "Espero no encontrarme con ninguna imperfección en estas armas.",
    "Me pregunto cuánto tiempo lleva forjar una espada de calidad.",
    "Estoy empezando a sentir la energía del metal caliente.",
    "Me gustaría descansar un rato después de una jornada en la fragua.",
    "Me pregunto qué técnicas de forja se emplean en estas obras maestras de metal.",
    "Espero no encontrarme con armas de baja calidad en el campo de batalla.",
    "Me pregunto cuánto tiempo lleva perfeccionar el arte de la herrería.",
    "Estoy empezando a sentir sed de la chispa del metal fundido.",
    "Me gustaría beber algo para refrescar mi garganta después de forjar.",
    "Me pregunto qué guerreros portarán estas armas y cuán valientes serán.",
    "Espero no encontrarme con enemigos formidables en el campo de batalla.",
    "Me pregunto cuánto tiempo llevará que estas armas sean legendarias.",
    "Estoy empezando a sentir el peso del acero en mis manos.",
    "Me gustaría abrigarme con una armadura resistente y bien forjada.",
    "Me pregunto qué historias de batalla contarán estas armas en el futuro.",
    "Espero que estas armas sean dignas de los héroes que las empuñarán.",
    "Me pregunto cuánto tiempo pasará antes de que estas armas sean probadas en combate.",
    "Estoy empezando a sentir la responsabilidad de forjar herramientas de guerra.",
    "Me gustaría estar en mi taller, concentrado en mi labor.",
    "Me pregunto qué desafíos me esperan en el mundo de la herrería y la forja.",
    "Espero que mis armas sean siempre confiables en manos de los guerreros.",
    "Me pregunto cuánto tiempo llevará perfeccionar mi técnica como herrero.",
    "Estoy empezando a sentirme orgulloso de cada arma que forjo.",
    "Me gustaría ver a los guerreros valientes que portarán mis creaciones.",
    "Me pregunto qué batallas épicas se librarán con estas armas en la mano.",
    "Espero que estas armas sean recordadas en la historia de las batallas.",
    "Me pregunto cuánto tiempo llevará antes de que mi nombre esté ligado al arte de la forja.",
    "Estoy empezando a sentirme emocionado por el destino de mis armas.",
    "Me gustaría seguir forjando muchas más armas poderosas.",
    "Me pregunto qué desafíos metalúrgicos me esperan en el camino.",
    "Espero que mis armas sean temidas en los campos de batalla.",
    "Me pregunto cuánto tiempo llevará hasta que forje la próxima obra maestra.",
    "Estoy empezando a sentir la satisfacción de crear armas que pueden cambiar el curso de una guerra."
    ],
inventario : [
    {name : "Pedernal", desc : "Piedra afilada que usualmente se utiliza para generar fuego, puedes equiparlo para ganar algo de ataque", tag_inventario: "Equipar", precio : 5, bioma : "Montaña", cantidad : 15},
    {name : "Pico de Cañerul", desc : "Pico de color verdoso con brillo resultante que, según los mineros, tiene una gran eficiencia y rendimiento en la labor de minería", tag_inventario: "Usar", precio : 100, bioma : "Montaña", cantidad : 3},
    {name : "Ballesta", desc : "Artefacto hecho de madera con un conjunto de engranajes que permiten  tensar la cuerda y lanzar flechas capaces de perforar armaduras, muchos caballeros la detestan", tag_inventario: "Equipar", precio : 250, bioma : "Prado", cantidad : 1},
    {name : "Daga", desc : "Muy afilada y de corto alcance, es el arma más usada para hacer traiciones", tag_inventario: "Equipar", precio : 200, bioma : "Prado", cantidad : 2},
    {name : "Carne seca", desc : "Carne bien preparada lista para comer en cualquier situación", tag_inventario: "Usar", precio : 20, bioma : "Poblado", cantidad : 15},
    {name : "Espada", desc : "Un clásico objeto alargado y cortante, es el arma más popular de los aventureros", tag_inventario: "Equipar", precio : 400, bioma : "Poblado", cantidad : 2},
    {name : "Escudo", desc : "La protección es esencial para los largos viajes ¡Ya que el combate esta en cada esquina!", tag_inventario: "Equipar", precio : 400, bioma : "Poblado", cantidad : 2},
    {name : "Cristal letal", desc : "Muy extraño objeto de color oscuro cristalino, procuras no mirarlo mucho directamente...", tag_inventario: "Usar", precio : 600, bioma : "???", cantidad : 1},
    {name : "Cristal de la confianza", desc : "Extraño objeto de color rosado cristalino, al mirarlo te resulta muy acogedor y familiar.", tag_inventario: "Usar", precio : 300, bioma : "Poblado", cantidad : 1}
]};