function inicio_comercio(e){
    let copia = JSON.parse(JSON.stringify(e));
    return copia;
}

const comercio_prado_1 = {nombre: "Comerciante Alex", conoce: false, finInventario: ["Comerciante Alex: ¡Me ha quedado sin existencias!","Comerciante Alex: ¡Muchas gracias por comprarlo todo!"], cabezal: "Tienda ambulante de Alex", src: "https://image.lexica.art/full_jpg/123d6551-e8a7-4c07-86d2-b71cd412ef9d",
frases: [
    "Que alegría poder encontrar a alguien amable en estos prados.",
    "Espero que el tiempo aguante.",
    "Me pregunto qué clase de criaturas viven en estos prados.",
    "Espero no encontrarme con ningún bandido.",
    "Me pregunto cuánto falta para llegar a la próxima ciudad.",
    "Estoy empezando a tener hambre.",
    "Me gustaría descansar un rato.",
    "Me pregunto qué clase de animales viven en estos bosques.",
    "Espero no encontrarme con ningún monstruo.",
    "Me pregunto cuánto falta para llegar a la próxima aldea.",
    "Estoy empezando a tener sed.",
    "Me gustaría beber algo de agua.",
    "Me pregunto qué clase de gente vive en esta zona.",
    "Espero no encontrarme con ningún mago malvado.",
    "Me pregunto cuánto falta para llegar a mi destino.",
    "Estoy empezando a tener frío.",
    "Me gustaría abrigarme.",
    "Me pregunto qué clase de aventuras me esperan en esta tierra.",
    "Espero no tener que luchar contra ningún dragón.",
    "Me pregunto cuánto falta para llegar a la próxima gran ciudad.",
    "Estoy empezando a tener miedo.",
    "Me gustaría estar en casa.",
    "Me pregunto qué clase de peligros me esperan en este mundo.",
    "Espero poder sobrevivir.",
    "Me pregunto cuánto falta para llegar a la próxima frontera.",
    "Estoy empezando a perder la esperanza.",
    "Me gustaría rendirme.",
    "Me pregunto qué clase de futuro me espera en este mundo.",
    "Espero poder encontrar mi lugar en la vida.",
    "Me pregunto cuánto falta para llegar a la próxima aventura.",
    "Estoy empezando a sentirme emocionado.",
    "Me gustaría vivir muchas más aventuras.",
    "Me pregunto qué clase de cosas me esperan en este mundo.",
    "Espero poder ver y hacer muchas cosas.",
    "Me pregunto cuánto falta para llegar a la próxima gran cosa.",
    "Estoy empezando a sentir curiosidad.",
    "Me gustaría aprender muchas cosas nuevas.",
    "Me pregunto qué clase de personas me esperan en este mundo.",
    "Espero poder conocer muchas personas.",
    "Me pregunto cuánto falta para llegar a la próxima gran reunión.",
    "Estoy empezando a sentirme feliz."
],
inventario : [
    {name : "Legumbres", desc : "Delicioso alimento muy rico vitaminicamente, da mucha energía", precio : 20, bioma : "Poblado", cantidad : 3},
    {name : "Piedra Rúnica", desc : "Piedra de un brillo azulado con unas marcas y símbolos extraños e incomprensibles...", precio : 200, bioma : "Prado", cantidad : 1},
    {name : "Daga", desc : "Muy afilada y de corto alcance, es el arma más usada para hacer traiciones", precio : 250, bioma : "Prado", cantidad : 1},
    {name : "Ballesta", desc : "Artefacto hecho de madera con un conjunto de engranajes que permiten  tensar la cuerda y lanzar flechas capaces de perforar armaduras, muchos caballeros la detestan", precio : 350, bioma : "Prado", cantidad : 1},
    {name : "Flores Silvestres", desc : "Conjunto de flores hermosas que tienen un aroma muy embriagador", precio : 30, bioma : "Prado", cantidad : 5},
    {name : "Bayas Silvestres", desc : "Unas bayas que crecen en los prados, ¡su sabor es sumamente dulce y delicioso!", precio : 15, bioma : "Prado", cantidad : 10},
]};

const comercio_sirena = {nombre: "Sirena", finInventario: ["Sirena: ¡Ya no tengo nada más que ofrecerte!","Sirena: ¡Muchas gracias viajero por tus servicios!"], cabezal: "Objetos del mar", src: "https://image.lexica.art/full_jpg/0f50af94-aa58-434d-9cd3-178fc4677603",
frases: [
    "El mar es un lugar inmenso, Un mundo lleno de vida. Hay peces de todos colores, Y criaturas grandes y pequeñas.",
    "Mar, eres el espejo del cielo, un mar de azules y verdes, un mar de sueños y misterios.",
    "El mar es un lugar maravilloso, Un lugar lleno de secretos. Es un lugar donde puedes perderte, Y encontrarte a ti mismo.",
    "En tus aguas cristalinas, los peces nadan libres, las ballenas juegan, y los delfines saltan.",
    "El mar es un lugar peligroso, Un lugar donde la tormenta puede golpear de repente. Pero también es un lugar hermoso, Un lugar donde puedes sentir la paz.",
    "En tus costas arenosas, los niños juegan, los enamorados se besan, y los viejos se sientan a recordar.",
    "El mar es un lugar maravilloso, Un lugar lleno de secretos. Es un lugar donde puedes perderte, Y encontrarte a ti mismo.",
    "En tus olas bravías, los barcos navegan, los pescadores faenan, y los piratas se esconden.",
    "El mar es un lugar de contrastes, Un lugar donde la calma y la tormenta se encuentran. Es un lugar donde la vida y la muerte coexisten.",
    "En tus aguas profundas, los tesoros se esconden, las sirenas habitan, y los monstruos marinos se ocultan.",
    "El mar es un lugar maravilloso, Un lugar lleno de secretos. Es un lugar donde puedes perderte, Y encontrarte a ti mismo.",
    "Mar, eres un lugar mágico, un lugar de sueños y aventuras, un lugar donde todo es posible.",
    "El mar es un lugar misterioso, Un lugar que nunca deja de sorprender. Es un lugar que siempre nos llama, Y nunca podemos dejar de ir.",
    "Mar, nos enseñas la belleza de la naturaleza, nos enseñas el poder de la vida, y nos enseñas el misterio del universo.",
    "Mar, eres un regalo de la naturaleza, un regalo que debemos cuidar, un regalo que debemos preservar.",
    "Mar, eres el espejo del cielo, un mar de azules y verdes, un mar de sueños y misterios."
],
inventario : [
    {name : "Algas Marinas", desc : "No hay mucho que describir, puedes lanzarlas por la borda o cocinarlas (aúnque su sabor no sea muy agradable)", precio : 5, bioma : "Mar", cantidad : 20},
    {name : "Escamas de Coral", desc : "Escamas grandes pertenecientes a alguna misteriosa criatura de las profundidades", precio : 150, bioma : "Mar", cantidad : 3},
    {name : "Cola de Tritón", desc : "Bella cola perteneciente a algún tritón que la habrá perdido para su desgracia", precio : 150, bioma : "Mar", cantidad : 3},
    {name : "Espuma de Sirena", desc : "Preciosas perlas color azulado muy raras de encontrar en la mar, según se dice, se forman con la última palabra una sirena", precio : 150, bioma : "Playa", cantidad : 3},
    {name : "Escudo de Arena", desc : "Escudo formado por diversas capas de arena que se van intercalando entre sí, ¡Aunque no lo parezca es muy resistente!", precio : 250, bioma : "Playa", cantidad : 2},
    {name : "Concha Marina", desc : "Bonita concha decorativa la cual puede alcanzar un buen precio en el mercado", precio : 100, bioma : "Playa", cantidad : 5},
    {name : "Pescado Fresco", desc : "¿A quien no le gusta este buen manjar de la mar?", precio : 20, bioma : "Playa", cantidad : 15},
    {name : "Romboide de arena celeste", desc : "Extraño artefacto que guarda en su interior un extraño y misterioso poder; dicen las leyendas que quien lo deshaga se podrá teletransportar", precio : 300, bioma : "Mar", cantidad : 1},
]};